services:
  # Base de donn√©es MariaDB
  glpi-db:
    image: mariadb:10.11
    container_name: glpi-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=glpidb
      - MARIADB_USER=glpi
      - MARIADB_PASSWORD=glpi_password
    volumes:
      - glpi-db-data:/var/lib/mysql

  glpi:
    image: diouxx/glpi
    container_name: glpi-app
    restart: always
    depends_on:
      - glpi-db
    environment:
      - GLPI_LANG=fr_FR
    ports:
      - "2222:22"

  # Proxy Nginx
  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - glpi

volumes:
  glpi-db-data:
